### ISSUE TITLE
[FR] Implement ERD Model for app

### ISSUE THREAD

**Issue by rileyhawk1417** [fred-juma/iGymHealth#20]
The [database](https://community.andela.com/c/health-team16-2022/erd-database-model-for-igymhealth) schema is meant to be implemented for both online & offline use within the application. In order to solve this issue it will need to be broken down into stages.

## Offline First:
- We prioritise on offline first to ensure the app can still function without internet connection.

### ToDo:
- [ ] Perform database functions offline.
    - [ ] Load the database.
    - [ ] Read from the database.
    - [ ] Save to the database.
    - [ ] Delete from the database.  
  
## Sync with cloud:
- This is when we sync the local database with our firebase instance.

### ToDo:
- [ ] Connect to the firebase instance.
    - [ ] Fetch from firebase.
    - [ ] Update local data & push new data to firebase.
        - [ ] In the event of conflict between firebase & local data, ask user which they want to keep.
